name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [macos]
        ruby: [ '3.2', '3.3' ]

    steps:
      - name: icu4c
        run: brew install icu4c
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install
      - name: Run tests ${{ matrix.rubyopt }}
        run: bundle exec rake RUBYOPT="${{ matrix.rubyopt }}"
